version: v2
managed:
  enabled: true
  override:
    - file_option: go_package_prefix
      value: github.com/rilldata/rill
plugins:
  - remote: buf.build/grpc-ecosystem/openapiv2:v2.16.2
    out: gen
    opt:
      - logtostderr=true
      - output_format=yaml
      - allow_merge=true,merge_file_name=rill/admin/v1/admin
      - disable_service_tags=true
