version: v1
managed:
  enabled: true
  go_package_prefix:
    default: github.com/rilldata/rill
plugins:
  - plugin: buf.build/grpc-ecosystem/openapiv2
    out: gen
    opt:
      - logtostderr=true
      - output_format=yaml
      - allow_merge=true,merge_file_name=rill/admin/v1/admin
      # - openapi_naming_strategy=simple # Removes "V1" prefix from types
      # - simple_operation_ids=true # Removes "AdminService_" prefix from operations
